### ISSUE TITLE
Cannot type a capital 'S'

### ISSUE THREAD

**Issue by jocopa3** [dude719/Reclass-2016#23]
Using the current source code, keyboard shortcuts/accelerators are still being listened for when typing in a text box. Because of this, typing a capital S in a text box (e.x. to rename a class or type a comment) pulls up the Save-As Menu rather than typing a literal 'S'.

A partial fix is to change the Save-As shortcut to Ctrl-Shift-S instead of Shift-S.

**Comment by jocopa3** [comment]
A more proper fix would be to override the _PreTranslateMessage_ function in whichever class handles the memory view/editor. The full function definition is:

`virtual BOOL PreTranslateMessage(MSG* pMsg)` 

In the PreTranslateMessage function, listen for when the message corresponds to the Shift-S message, then return TRUE when the Shift-S message is encountered when the user is editing text.

**Comment by dude719** [comment]
Yeah I'll fix that, haven't had time to work on this. Was annoying me last week when I was using the current source lol

**Comment by Timboy67678** [comment]
was actually gonna say this, forgot about it
